import java.util.*;
import java.util.Random;

public class random {

   public static void game(int x)
   {
    Scanner sc=new Scanner(System.in);
    int y,n=10,c=0; // variable n is no of chances we are creating
    //variable c is the boolean variable which denotes chances are not finished
    while(n>0)
    {
    System.out.println("Input your no : ");
    y=sc.nextInt();//variable y is our input to match the no generated by computer
    if(x<y)
    {
        n--;
        System.out.println("No is High Think it Smaller");
        System.out.println("Attempts left ="+ n);
        c=0;
    }
    else if(x>y)
    {
        n--; 
        System.out.println("No is Low Think more Bigger");
        System.out.println("Attempts left ="+ n);
        c=0;
    }
    else
    {
        System.out.println("Congratulation for the correct guess");
        System.out.println("score = "+n*10);
      
       c=1;
        break;
    }
  
    }
    sc.close();
     if(c==0)System.out.println("Sorry try again :");//our attempts are exhausted
   }
    public static void main(String args[])
    {    Random no=new Random();
        int x;
        x=no.nextInt(100);//our random no for the game
        System.out.println("..........Welcome to the number guessing Game............");
        System.out.println("You will be given 10 guesses for guesing the game");
        System.out.println("You will be deducted 10 points on each wrong attempts");
        game(x);
    }
}
